//! Inserts text into the focused field: put it on the clipboard, send the
//! paste shortcut, then restore whatever the user had on the clipboard.

use std::time::Duration;

use anyhow::Result;

/// How long the target app gets to read the clipboard before we restore it.
const RESTORE_DELAY: Duration = Duration::from_millis(250);

pub use platform::Injector;

#[cfg(target_os = "macos")]
mod platform {
    use super::*;
    use objc2::rc::Retained;
    use objc2::runtime::ProtocolObject;
    use objc2_app_kit::{NSPasteboard, NSPasteboardItem, NSPasteboardTypeString};
    use objc2_core_graphics::{
        CGEvent, CGEventFlags, CGEventSource, CGEventSourceStateID, CGEventTapLocation, CGEventType,
    };
    use objc2_foundation::{NSArray, NSData, NSString};

    const KVK_ANSI_V: u16 = 9;
    const KVK_COMMAND: u16 = 55;

    /// Markers from nspasteboard.org that tell clipboard managers (Maccy,
    /// Raycast, Alfred, Paste...) not to record this entry.
    const PRIVACY_MARKERS: [&str; 3] = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ];

    pub struct Injector;

    type SavedItem = Vec<(Retained<NSString>, Retained<NSData>)>;

    impl Injector {
        pub fn new() -> Result<Self> {
            Ok(Self)
        }

        pub fn paste(&mut self, text: &str) -> Result<()> {
            let pb = NSPasteboard::generalPasteboard();
            let saved = save(&pb);

            pb.clearContents();
            let item = NSPasteboardItem::new();
            // SAFETY: reading an immutable AppKit constant that is set at load time.
            item.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString });
            for m in PRIVACY_MARKERS {
                item.setData_forType(&NSData::new(), &NSString::from_str(m));
            }
            write(&pb, vec![item]);
            let ours = pb.changeCount();

            send_cmd_v();

            std::thread::sleep(RESTORE_DELAY);
            // Only restore if nothing else touched the clipboard meanwhile.
            if pb.changeCount() == ours {
                pb.clearContents();
                let items = saved
                    .into_iter()
                    .map(|types| {
                        let it = NSPasteboardItem::new();
                        for (t, d) in types {
                            it.setData_forType(&d, &t);
                        }
                        it
                    })
                    .collect();
                write(&pb, items);
            }
            Ok(())
        }
    }

    fn save(pb: &NSPasteboard) -> Vec<SavedItem> {
        let Some(items) = pb.pasteboardItems() else {
            return Vec::new();
        };
        items
            .iter()
            .map(|it| {
                it.types()
                    .iter()
                    .filter_map(|t| it.dataForType(&t).map(|d| (t, d)))
                    .collect()
            })
            .collect()
    }

    fn write(pb: &NSPasteboard, items: Vec<Retained<NSPasteboardItem>>) {
        if items.is_empty() {
            return;
        }
        let objs: Vec<_> = items
            .into_iter()
            .map(ProtocolObject::from_retained)
            .collect();
        pb.writeObjects(&NSArray::from_retained_slice(&objs));
    }

    /// Sends Cmd down, V down, V up, Cmd up, like a real keyboard. Sending only
    /// V with the Command flag leaves key listeners (including our own hotkey
    /// listener) believing Cmd is still held, so the next hotkey press is seen
    /// as Cmd+hotkey and ignored.
    fn send_cmd_v() {
        let src = CGEventSource::new(CGEventSourceStateID::HIDSystemState);
        let steps = [
            (KVK_COMMAND, true, CGEventFlags::MaskCommand),
            (KVK_ANSI_V, true, CGEventFlags::MaskCommand),
            (KVK_ANSI_V, false, CGEventFlags::MaskCommand),
            (KVK_COMMAND, false, CGEventFlags(0)),
        ];
        for (key, down, flags) in steps {
            if let Some(ev) = CGEvent::new_keyboard_event(src.as_deref(), key, down) {
                if key == KVK_COMMAND {
                    CGEvent::set_type(Some(&ev), CGEventType::FlagsChanged);
                }
                // Set flags explicitly so modifiers the user is still holding
                // (e.g. the hotkey) don't turn this into Cmd+Opt+V.
                CGEvent::set_flags(Some(&ev), flags);
                CGEvent::post(CGEventTapLocation::HIDEventTap, Some(&ev));
            }
        }
    }
}

#[cfg(target_os = "linux")]
mod platform {
    //! Wayland and X11: clipboard via arboard (wlr/ext data-control or X11),
    //! keystrokes via a uinput virtual keyboard, which works on every
    //! compositor including GNOME. Needs write access to /dev/uinput.
    use super::*;
    use anyhow::Context;
    use evdev::{AttributeSet, EventType, InputEvent, KeyCode, uinput::VirtualDevice};

    pub struct Injector {
        kbd: VirtualDevice,
        clipboard: arboard::Clipboard,
    }

    impl Injector {
        pub fn new() -> Result<Self> {
            let mut keys = AttributeSet::<KeyCode>::new();
            keys.insert(KeyCode::KEY_LEFTCTRL);
            keys.insert(KeyCode::KEY_V);
            // Created once at startup: compositors need a moment to pick up
            // a new input device, so creating it per-paste would drop keys.
            let kbd = VirtualDevice::builder()
                .context("cannot open /dev/uinput (see README: Linux setup)")?
                .name("sayit virtual keyboard")
                .with_keys(&keys)?
                .build()?;
            let clipboard = arboard::Clipboard::new().context("clipboard unavailable")?;
            Ok(Self { kbd, clipboard })
        }

        pub fn paste(&mut self, text: &str) -> Result<()> {
            let saved = self.clipboard.get_text().ok();
            self.clipboard.set_text(text)?;
            std::thread::sleep(Duration::from_millis(30));

            let key = |k: KeyCode, v| InputEvent::new(EventType::KEY.0, k.code(), v);
            self.kbd
                .emit(&[key(KeyCode::KEY_LEFTCTRL, 1), key(KeyCode::KEY_V, 1)])?;
            self.kbd
                .emit(&[key(KeyCode::KEY_V, 0), key(KeyCode::KEY_LEFTCTRL, 0)])?;

            if let Some(prev) = saved {
                std::thread::sleep(RESTORE_DELAY);
                if self.clipboard.get_text().ok().as_deref() == Some(text) {
                    self.clipboard.set_text(prev)?;
                }
            }
            Ok(())
        }
    }
}
